### ISSUE TITLE
fails to install on sage 8.9 with python3

### ISSUE THREAD

**Issue by fchapoton** [mmasdeu/darmonpoints#1]
message:

```
Collecting darmonpoints
  Downloading https://files.pythonhosted.org/packages/8b/02/3de7d8a8be4431c951a4a81734f20110c8929c83de9b04afe6f3df4b9c23/darmonpoints-3.2.0.tar.gz (161kB)
    100% |████████████████████████████████| 163kB 3.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gaxlw9zf/darmonpoints/setup.py", line 5, in <module>
        import urllib2
    ModuleNotFoundError: No module named 'urllib2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gaxlw9zf/darmonpoints/

```

**Comment by fchapoton** [comment]
https://stackoverflow.com/questions/2792650/import-error-no-module-name-urllib2
